{{- if .Values.awsIngress.enabled }}
{{- $fullName := include "k8-application.fullname" . -}}
{{- range $key, $lb := .Values.awsIngress.loadbalancers }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $key }}
  labels:
    {{- include "k8-application.labels" $ | nindent 4 }}
    {{- include "k8-application.customLabels" $ | indent 4 }}
  {{- with $lb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $lb.spec }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
