{{- if .Values.configmap.enabled -}}
{{- range $i, $config := .Values.configmap.configs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8-application.fullname" $ }}-{{ $config.name }}
  labels:
    {{- include "k8-application.labels" $ | nindent 4 }}
    {{- include "k8-application.customLabels" $ | indent 4 }}
data:
  {{- range $key, $val := $config.values }}
  {{ $key }} : {{$val | quote}}
  {{- end }}
{{- end -}}
{{- end -}}